version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  reviewers:
  - baruchiro
  assignees:
  - baruchiro
  target-branch: "upgrades"
  ignore:
  - dependency-name: electron
    versions:
    - "> 5.0.13"

- package-ecosystem: npm
  directory: "/nuxt/"
  schedule:
    interval: monthly
  target-branch: "nuxt-upgrades"
