version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '03:00'
  open-pull-requests-limit: 5
  reviewers:
  - baruchiro
  assignees:
  - baruchiro
  ignore:
  - dependency-name: electron
    versions:
    - "> 5.0.13"

- package-ecosystem: npm
  directory: "/nuxt/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
