name: Node CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: lint
        run: |
          yarn
          yarn lint
        
  test:

    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99.0

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y xvfb graphicsmagick
        npm install -g xvfb-maybe
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: yarn install
      run: yarn
    - name: yarn unit
      run: yarn unit
    - name: yarn e2e
      run: yarn e2e

  build:

    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Set version in Env
      shell: bash
      run: |
        echo ::set-env name=package_version::`awk -F ':' '/version/ {print $2}' package.json | sed 's/\"//g' | sed 's/,//g' | sed 's/ //g'`
        echo "Version is `awk -F ':' '/version/ {print $2}' package.json | sed 's/\"//g' | sed 's/,//g' | sed 's/ //g'`"
    - uses: actions/github-script@0.3.0
      name: Check if current version is a published release (by release tag)
      id: check_release
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        # debug: true
        script: |
          const result = await github.repos.listReleases({
            owner: 'baruchiro',
            repo: 'israeli-bank-scrapers-desktop'
          })
          // console.log(result)
          const release_tags = result.data.filter(release => !release.draft).map(release => release.tag_name)
          // console.log(release_tags)
          const publishToRelease = !release_tags.includes('v${{ env.package_version }}')
          console.log('publishToRelease: ' + publishToRelease)
          console.log('Will not publish to release in PR')
          return publishToRelease
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@2a2b003682661733922241b9af1c4c1c789f30f1
      # Only install Snapcraft  on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      with:
        # Log in to  Snap Store
        snapcraft_token: ${{ secrets.snapcraft_token }}
    - name: Build & release Electron app
      env:
        GOOGLE_SERVICE_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.check_release.outputs.result
      run: |
        yarn
        yarn build --publish onTagOrDraft
