name: Build/Release

on:
  push:
    branches: baruchiro-patch-1

jobs:
  release:

    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]

    steps:
    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const result = await github.repos.listReleases({
            'baruchiro',
            'israeli-bank-scrapers-desktop'
          })
          console.log(result)
    - uses: actions/checkout@v1
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@2a2b003682661733922241b9af1c4c1c789f30f1
      # Only install Snapcraft on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      with:
        # Log in to Snap Store
        snapcraft_token: ${{ secrets.snapcraft_token }}
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@aab12df5d99568b8426a07695135a977d30c9a95
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}

        # macOS code signing certificate
        #mac_certs: ${{ secrets.mac_certs }}
        #mac_certs_password: ${{ secrets.mac_certs_password }}

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        # release: ${{ `git tag | grep ^v`awk -F ':' '/version/ {print $2}' package.json | sed 's/\"//g' | sed 's/,//g' | sed 's/ //g'`$ | wc -l`==0 }}
